name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21'
      - name: Test
        run: go test -race -timeout 30m -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Coverage
        uses: codecov/codecov-action@v4
        with:
          file: coverage.txt
  advanced-security:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21'
      - uses: github/codeql-action/init@v2
        with:
          languages: 'go'
      - uses: github/codeql-action/autobuild@v2
      - uses: github/codeql-action/analyze@v2
  release:
    needs:
      - test
      - advanced-security
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21'
      - run: make install-release-tool new-patch-release
